test_that("the labelling space contains the exact two-group test", {
  sim <- mt_simulate(n = c(A = 4, B = 5), n_ch = 4, n_epochs = 6, seed = 3)
  sp <- mt_label_space(sim$features)
  expect_equal(nrow(sp$labelings), 2^9 - 2)
  loc <- mt_locate(sp, sim$group == "A")
  res <- metric_t(sim$features, sim$group, comparisons = list(c("A", "B")), exact = TRUE, wy_family = "all")
  expect_equal(loc$T, res$table$T, tolerance = 1e-8)
  expect_equal(loc$p_exact, res$table$p_raw, tolerance = 1e-12)
  expect_equal(loc$p_min, res$table$p_min, tolerance = 1e-12)
  expect_equal(loc$n_same_size, rep(choose(9, 4), nrow(loc)))
  expect_true(all(sp$summary$m_eff_wPLI > 0 & sp$summary$reversal_share >= 0 & sp$summary$reversal_share <= 1))
})

test_that("the trend version reduces to the two-group statistic and enumerates strata", {
  sim <- mt_simulate(n = c(A = 3, B = 4), n_ch = 4, n_epochs = 6, seed = 4)
  x <- as.numeric(sim$group == "A")
  tr <- metric_t_trend(sim$features, x, method = "linear", exact = TRUE)
  res <- metric_t(sim$features, sim$group, comparisons = list(c("A", "B")), exact = TRUE, wy_family = "all")
  expect_equal(tr$table$T, res$table$T, tolerance = 1e-8)
  expect_equal(tr$table$p, res$table$p_raw, tolerance = 1e-12)
  expect_equal(tr$n_perm, factorial(7))
  set.seed(5); y <- runif(7)
  st <- c("a", "a", "a", "b", "b", "b", "b")
  tr2 <- metric_t_trend(sim$features, cbind(y = y, z = rev(y)), strata = st)
  expect_true(tr2$exact)
  expect_equal(tr2$n_perm, factorial(3) * factorial(4))
  expect_true(all(tr2$table$p > 0 & tr2$table$p <= 1))
  expect_true(all(tr2$table$p_family >= tr2$table$p - 1e-12))
  mc <- metric_t_trend(sim$features, y, strata = st, exact = FALSE, n_perm = 200)
  expect_false(mc$exact)
  expect_equal(mc$table$T, tr2$table$T[tr2$table$covariate == "y"], tolerance = 1e-8)
})
